version: '3.3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: nodemon app.js
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV=development  
    ports:
      - '8080:8080'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    networks:
      - api-tier
volumes: 
  db-data:

networks: 
  api-tier:
